export type IPermissionName =
  | "users:read"
  | "users:create"
  | "users:update"
  | "users:delete"
  | "roles:read"
  | "roles:create"
  | "roles:update"
  | "roles:delete"
  | "permissions:read"
  | "website-users:read"
  | "website-users:create"
  | "website-users:update"
  | "website-users:delete"
  | "blog-categories:read"
  | "blog-categories:create"
  | "blog-categories:update"
  | "blog-categories:delete"
  | "blog-authors:read"
  | "blog-authors:create"
  | "blog-authors:update"
  | "blog-authors:delete"
  | "blog-tags:read"
  | "blog-tags:create"
  | "blog-tags:update"
  | "blog-tags:delete"
  | "blogs:read"
  | "blogs:create"
  | "blogs:update"
  | "blogs:delete"
  | "blogs:publish"
  | "blogs:revalidate"
  | "blog-categories:revalidate"
  | "blog-tags:revalidate"
  | "blog-authors:revalidate"
  | "services:read"
  | "services:create"
  | "services:update"
  | "services:delete"
  | "customers:read"
  | "customers:create"
  | "customers:update"
  | "customers:delete"
  | "bills:read"
  | "bills:create"
  | "bills:update"
  | "bills:delete"
  | "catalogues:read"
  | "catalogues:create"
  | "catalogues:update"
  | "catalogues:delete"
  | "inquiries:read"
  | "inquiries:update"
  | "social-posts:read"
  | "social-posts:create"
  | "social-posts:update"
  | "social-posts:delete";

export type IPermission = {
  id: string;
  slug: IPermissionName;
  label: string | null;
  resource: string;
  action: string;
  description: string | null;
  createdAt: string;
};
