import {
  IconBabyBottle,
  IconBabyCarriage,
  IconBalloon,
  IconBed,
  IconBuildingPavilion,
  IconCake,
  IconCamera,
  IconConfetti,
  IconCrown,
  IconDiamond,
  IconDisc,
  IconFlame,
  IconFlower,
  IconGift,
  IconGlassCocktail,
  IconHeart,
  IconMusic,
  IconPalette,
  IconSchool,
  IconScissors,
  IconSparkles,
  IconStar,
  IconSun,
  IconUsers,
} from '@tabler/icons-react'

/** Thin-line icon per service slug (replaces emoji on the cards). */
export const SERVICE_ICONS: Record<string, typeof IconCrown> = {
  'marriage-decoration': IconCrown,
  receptions: IconGlassCocktail,
  engagement: IconDiamond,
  varmala: IconFlower,
  'bride-groom-entry': IconUsers,
  'mirror-entry': IconSparkles,
  'bridal-doli': IconBuildingPavilion,
  'room-decoration': IconBed,
  'haldi-mehndi': IconSun,
  mehndi: IconPalette,
  'garba-entry': IconMusic,
  vanarasam: IconFlame,
  'bride-to-be': IconConfetti,
  'besna-decoration': IconGift,
  'birthday-celebration': IconCake,
  'baby-shower': IconBabyCarriage,
  'chhathi-pujan': IconBabyBottle,
  'anniversary-decoration': IconHeart,
  'party-decoration': IconBalloon,
  'farewell-party-decoration': IconSchool,
  opening: IconScissors,
  'festival-celebration': IconStar,
  'dj-orchestra': IconDisc,
  photography: IconCamera,
}

export const getServiceIcon = (slug: string): typeof IconCrown =>
  SERVICE_ICONS[slug] ?? IconSparkles
